"""Pydantic schemas for Milestone 13: Student Device Registration & Primary Device Trust."""

import datetime
import uuid
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class DeviceRegistrationChallengeRequest(BaseModel):
    """Request payload to initiate device registration challenge."""

    public_key: str = Field(
        ...,
        description="Candidate Ed25519 public key in PEM, Base64, or Hex format.",
    )
    installation_id: uuid.UUID | None = Field(
        default=None,
        description="Unique application installation UUID for telemetry.",
    )
    platform: str | None = Field(
        default=None,
        max_length=30,
        description="Operating system platform (e.g. android, ios).",
    )
    device_label: str | None = Field(
        default=None,
        max_length=100,
        description="Descriptive device label (e.g. Samsung Galaxy S23, iPhone 15).",
    )
    app_version: str | None = Field(
        default=None,
        max_length=30,
        description="Client mobile application semantic version string.",
    )


class DeviceRegistrationChallengeResponse(BaseModel):
    """Cryptographic challenge returned to candidate device."""

    challenge_id: uuid.UUID
    canonical_challenge: str
    expires_at: datetime.datetime
    algorithm: str = "Ed25519"
    protocol_version: str = "DEVICE_REGISTRATION_V1"
    candidate_fingerprint: str


class DeviceRegistrationConfirmRequest(BaseModel):
    """Payload to confirm initial device registration by proving key possession."""

    challenge_id: uuid.UUID = Field(
        ...,
        description="ID of the issued registration challenge.",
    )
    signature: str = Field(
        ...,
        description="Ed25519 signature over canonical challenge bytes.",
    )


class DeviceReplacementCreateRequest(BaseModel):
    """Student request to replace registered primary device with new candidate device."""

    candidate_challenge_id: uuid.UUID = Field(
        ...,
        description="ID of registration challenge generated by new candidate phone.",
    )
    candidate_signature: str = Field(
        ...,
        description="Signature over challenge proving possession of new candidate private key.",
    )
    reason: str = Field(
        ...,
        min_length=5,
        max_length=500,
        description="Student justification for device replacement (e.g. phone upgrade, lost).",
    )


class DeviceReplacementReviewRequest(BaseModel):
    """Staff review action payload for approving or rejecting replacement."""

    review_note: str | None = Field(
        default=None,
        max_length=500,
        description="Mandatory or optional justification for replacement review decision.",
    )


class DeviceStatusUpdateRequest(BaseModel):
    """Administrative payload for device suspension, reactivation, or revocation."""

    reason: str = Field(
        ...,
        min_length=3,
        max_length=500,
        description="Audit reason for device state transition.",
    )


class TrustedDeviceResponse(BaseModel):
    """Safe public representation of a registered student device."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    university_id: uuid.UUID
    user_id: uuid.UUID
    student_id: uuid.UUID
    device_role: str
    public_key_fingerprint: str
    short_fingerprint: str = ""
    installation_id: uuid.UUID | None = None
    platform: str | None = None
    device_label: str | None = None
    app_version: str | None = None
    status: str
    activated_at: datetime.datetime | None = None
    suspended_at: datetime.datetime | None = None
    revoked_at: datetime.datetime | None = None
    replaced_at: datetime.datetime | None = None
    created_at: datetime.datetime


class DeviceReplacementResponse(BaseModel):
    """Details of a device replacement request."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    university_id: uuid.UUID
    student_id: uuid.UUID
    student_user_id: uuid.UUID
    student_name: str | None = None
    student_number: str | None = None
    old_device_id: uuid.UUID
    old_device_fingerprint: str | None = None
    candidate_fingerprint: str
    candidate_platform: str | None = None
    candidate_device_label: str | None = None
    reason: str
    status: str
    requested_at: datetime.datetime
    reviewed_at: datetime.datetime | None = None
    reviewed_by_user_id: uuid.UUID | None = None
    review_note: str | None = None
    approved_device_id: uuid.UUID | None = None


class StudentDeviceStatusResponse(BaseModel):
    """Aggregated device status for the authenticated student."""

    has_active_device: bool
    active_device: TrustedDeviceResponse | None = None
    pending_replacement: DeviceReplacementResponse | None = None


class DeviceTrustEventResponse(BaseModel):
    """Audit ledger record of a device trust transition."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    university_id: uuid.UUID
    target_user_id: uuid.UUID
    target_student_id: uuid.UUID
    device_id: uuid.UUID | None = None
    replacement_request_id: uuid.UUID | None = None
    event_type: str
    actor_user_id: uuid.UUID | None = None
    reason: str | None = None
    event_metadata: dict[str, Any] | None = None
    created_at: datetime.datetime


class DeviceProofSchema(BaseModel):
    """Cryptographic attendance presence proof submitted by student primary device."""

    version: str = Field(
        default="DEVICE_PROOF_V1",
        description="Device proof protocol version string.",
    )
    device_id: uuid.UUID = Field(
        ...,
        description="UUID of registered primary device claiming attendance.",
    )
    proof_id: uuid.UUID = Field(
        ...,
        description="Random submission proof UUID for deduplication and audit.",
    )
    algorithm: str = Field(
        default="Ed25519",
        description="Signature algorithm.",
    )
    signature: str = Field(
        ...,
        description="Asymmetric device signature over canonical presence payload.",
    )
